# Site settings

baseurl: ""
available: "ru, it"

# SEO related

title: "Greentea OS"
twitter: "@greenteaos"
author: "Greentea OS Team"
description: "Greentea OS is a free Windows-compatible operating system written from scratch, but more user and production oriented. We would first make it *actually* usable for day-to-day use."
image: "https://greenteaos.github.io/images/opengraph.png"
url: "https://greenteaos.github.io"
theme-color: "#f8f8f8"

# Build settings

markdown: kramdown
