# Site settings

baseurl: ""
available: "en, de, fr, es, ru, it, ch, jp"

# SEO related

title: "Greentea OS"
twitter: "@greenteaos"
author: "Greentea OS"
description: "Greentea OS is a free operating system"
image: "https://greenteaos.github.io/assets/images/opengraph.png"
url: "https://greenteaos.github.io"
theme-color: "#528a3f"

# Structure

social:
  name: Greentea OS
  links:
    - https://t.me/greenteaos
    - https://twitter.com/greenteaos
    - https://github.com/greenteaos

# Build settings

markdown: kramdown
highlighter: rouge
plugins:
   - jemoji
   - jekyll-seo-tag
   - jekyll-sitemap
kramdown:
  autolink: true
  input: GFM
  syntax_highlighter: rouge
